openapi: 3.0.3
info:
  version: 0.0.1
  title: BU - VDU VFS
  description:
    Testing API for my Bachelor work...
tags:
  - name: Ping
  - name: Auth Key
  - name: File
paths:
  /ping:
    get:
      summary: To test a connection (to do a ping).
      operationId: ping
      tags:
        - Ping
      responses:
        '204': 
          description: The server successfully processed the request, and is not returning any content.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            X-Client-Ip:
              description: The originating IP address of the request sent by a client connecting to a server.
              schema:
                type: string
  /auth/key:
      get:
        summary: Authorization token (key) renewal.
        operationId: renewalKey
        tags:
          - Auth Key
        parameters: 
        - in: header
          name: X-Api-Key
          description: The last auth key token.
          required: true
          schema:
            type: string
        responses:
          '200': 
            description: The success.
            headers:
              X-Api-Key:
                description: The new auth key token.
                schema:
                  type: string
              Date:
                description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
                schema:
                  type: string
              Expires:
                description: Gives the date/time after which the response is considered stale (in "HTTP-date" format as defined by RFC 7231).
                schema:
                  type: string
          '401':
            description: Invalid X-API-Key.
            headers:
              Date:
                description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
                schema:
                  type: string
              Expires:
                description: Gives the date/time after which the response is considered stale (in "HTTP-date" format as defined by RFC 7231).
                schema:
                  type: string
      post:
        summary: Generate a new authorization token (key) for the first time.
        operationId: generateKey
        tags:
          - Auth Key
        parameters: 
        - in: header
          name: From
          description: The email address/username/etc. of the user making the request.
          required: true
          schema:
            type: string
        requestBody:
          content:
            "text/plain":
              schema:
                type: string
              examples: 
                clientSecret:
                  summary: "Client secret"
                  value: "'StrongClientSecret@123' //can be an empty in the case of client certificate/TLS authentication"
          required: true
        responses:
          '201': 
            description: The success.
            headers:
              X-Api-Key:
                description: The new auth key token.
                schema:
                  type: string
              Date:
                description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
                schema:
                  type: string
              Expires:
                description: Gives the date/time after which the response is considered stale (in "HTTP-date" format as defined by RFC 7231).
                schema:
                  type: string
          '401': 
            description: Invalid From and/or the user’s client secret
            headers:
              Date:
                description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
                schema:
                  type: string
              Expires:
                description: Gives the date/time after which the response is considered stale (in "HTTP-date" format as defined by RFC 7231).
                schema:
                  type: string
      delete:
        summary: Authorization token (key) invalidation.
        operationId: invalidateKey
        tags:
          - Auth Key
        parameters: 
        - in: header
          name: X-Api-Key
          description:  The last auth key token.
          required: true
          schema:
            type: string
        responses:
          '204': 
            description: The success.
            headers:
              Date:
                description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
                schema:
                  type: string
          '401': 
            description: Invalid From and/or the user’s client secret.
            headers:
              Date:
                description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
                schema:
                  type: string 
  /file/{file-access-token}:
    get:
      summary: Get the content of a file available by the given access token.
      operationId: getFile
      tags:
        - File
      parameters: 
      - in: path
        name: file-access-token
        required: true
        schema:
          type: string
      - in: header
        name: X-Api-Key
        description:  The last auth key token.
        required: true
        schema:
          type: string
      responses:
        '200': 
          description: The success.
          headers:
            Allow: 
              description: Valid methods for a specified resource (GET for read-only, POST for write-only, GET POST for the ability to read multiple times and also write).
              schema:
                type: string
            Content-Encoding:
              description: The type of encoding used on the data.
              schema:
                type: string
            Content-Length:
              description: The length of the response body in octets (8-bit bytes).
              schema:
                type: string
            Content-Location:
              description: An alternate location for the returned data (a filename).
              schema:
                type: string
            Content-MD5:
              description: A Base64-encoded binary MD5 sum of the content of the response.
              schema:
                type: string
            Content-Type: 
              description: The MIME type of this content.
              schema:
                type: string
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
            Last-Modified: 
              description: The last modified date for the requested object (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
            ETag: 
              description: An identifier for a specific version of a resource, i.e., a version number.
              schema:
                type: string
          content: 
            "*/*":
              schema:
                type: string
              examples: 
                fileContent:
                  summary: "Content of the file"
                  value: "'conent of requested file'"
        '401': 
          description: Invalid X-API-Key.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
        '404': 
          description: The requested resource by the file-access-token could not be found.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
        '405': 
          description: A request method is not supported for the requested resource, i.e., the resource is write-only (could be read before, but cannot be read now).
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
        '408':   
          description: The client did not produce a request within the time that the server was prepared to wait for the upload.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
    post:
      summary: Post/upload the content of a file available by the given access token.
      operationId: uploadFile
      tags:
        - File
      parameters: 
      - in: path
        name: file-access-token
        required: true
        schema:
          type: string
      - in: header
        name: X-Api-Key
        description:  The last auth key token.
        required: true
        schema:
          type: string
      - in: header
        name: Content-Encoding
        description: The type of encoding used on the data.
        required: true
        schema:
          type: string
      - in: header
        name: Content-Length
        description: The length of the request body in octets (8-bit bytes).
        required: true
        schema:
          type: string
      - in: header
        name: Content-Location
        description: An alternate location for the data (a new filename if renamed by the client).
        required: true
        schema:
          type: string
      - in: header
        name: Content-MD5
        description: A Base64-encoded binary MD5 sum of the content of the request.
        required: true
        schema:
          type: string
      - in: header
        name: Content-Type
        description: The MIME type of this content.
        required: true
        schema:
          type: string
      requestBody:
        content:
          "*/*":
            schema:
              type: string
            examples: 
              fileContent:
                summary: "Content of the file"
                value: "'conent of uploaded file'"
        required: true
      responses:
        '201': 
          description: The success and the file access token remains valid.
          headers:
            Allow: 
              description: Valid methods for a specified resource (GET for read-only, POST for write-only, GET POST for the ability to read multiple times and also write).
              schema:
                type: string
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
            ETag: 
              description: An identifier for a specific version of a resource, i.e., a version number.
              schema:
                type: string
        '205': 
          description: The success and the file access token was invalidated.
          headers:
            Allow: 
              description: Valid methods for a specified resource (GET for read-only, POST for write-only, GET POST for the ability to read multiple times and also write).
              schema:
                type: string
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
            ETag: 
              description: An identifier for a specific version of a resource, i.e., a version number.
              schema:
                type: string
        '401': 
          description: Invalid X-API-Key
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
        '404': 
          description: The requested resource by the file-access-token could not be found.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
        '405': 
          description: A request method is not supported for the requested resource, i.e., the resource is read-only.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
        '408':   
          description: The client did not produce a request within the time that the server was prepared to wait for the upload.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
        '409':   
          description: Indicates that the request could not be processed because of conflict in the current state of the resource, such as an edit conflict between multiple simultaneous updates.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
            Expires: 
              description: Gives the date/time after which the response is considered stale so its new version cannot be posted (in "HTTP-date" format as defined by RFC 7231).
              schema:
                type: string
    delete:
      summary: To invalid the given file access token.
      operationId: invalidFile
      tags:
        - File
      parameters: 
      - in: path
        name: file-access-token
        required: true
        schema:
          type: string
      - in: header
        name: X-Api-Key
        description:  The last auth key token.
        required: true
        schema:
          type: string
      responses:
        '204': 
          description: The success.
          headers:            
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
        '401': 
          description: Invalid X-API-Key.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
        '404': 
          description: The requested resource by the file-access-token could not be found.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string
        '408':   
          description: The client did not produce a request within the time that the server was prepared to wait for the upload.
          headers:
            Date:
              description: The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 7231 Date/Time Formats).
              schema:
                type: string